### PR TITLE
Fix level up animation in the Results screen

### PR DESCRIPTION
**Pull request by F121Live**
This change makes the original level up animations show up
[https://imgur.com/a/a1PnwNO](https://imgur.com/a/a1PnwNO)

### CODE REVIEW

**Comment by fluofoxxo** [comment]
This PR does not build; I will merge and create a commit to fix issues.

**Comment by fluofoxxo** [comment]
Cancelled. This PR depends too deeply on RunnersRevival functionality, specifically with the campaignConf parser. Such functionality will need to merged upstream before this fix can be applied.

**Comment by F121Live** [comment]
Woops, I forgot about that 😭
I genuinely thought this was a thing in base outrun, my bad

**Comment by F121Live** [comment]
I'll try to adapt it when I get the time

**Pull request merged**
