### PR TITLE
Fix results screen XP bug (part 1)

### PR DESCRIPTION
**Pull request by FairPlay137**
The bug in question was mainly a visual glitch preventing you from seeing how much XP was gained during the run.

### CODE REVIEW

**Comment by FairPlay137** [comment]
It appears that this will require more work, as Sonic Runners' XP system and the currently implemented XP system don't line up.

**Comment by fluofoxxo** [comment]
Any progress on this?

**Comment by FairPlay137** [comment]
I haven't figured out where the problem truly lies, so I'm gonna close this PR.
If I make any breakthroughs, I'll either make a new PR or reopen this one.

**Comment by FairPlay137** [comment]
Leveling up is currently not shown properly; more research is needed to figure out how that works.

**Comment by fluofoxxo** [comment]
Any progress on this?

**Comment by MasterGamingYT** [comment]
idk

**Comment by MasterGamingYT** [comment]
this is temmieflakes btw

**Comment by FairPlay137** [comment]
Not yet. I'd say rename this PR to part 1 and I'll create a part 2 with the level-up animation fixed.

**Comment by fluofoxxo** [comment]
Then expect a merge sometime in the near future! Excited to bring this feature to the table.

**Comment by FairPlay137** [comment]
Will be reworked to address both the level up issue and the XP gain issue.

**Pull request closed without merging**
